### PR TITLE
feat: Memory limit environment variable

### PR DESCRIPTION
**Pull request by madmath03**
:sparkles: Memory limit environment variable

### CODE REVIEW

**Comment by loelkes** [comment]
This would be really nice. @thomascube Is there a reason this was not merged yet? Is there something we can do?

**Review by williamdes — APPROVED** [review]

**Comment by thomascube** [comment]
The change in general is accepted. Please rebase or create a new PR.

**Comment by pabzm** [comment]
@madmath03 Would you be interested to revive this PR and fix the conflicts?

**Comment by pabzm** [comment]
I'm closing this, since no one is working on it currently and I don't want stale PRs lingering around. If someone want's to pick it up, please re-open or let me know.

**Pull request closed without merging**
