### PR TITLE
Add execute permission

### PR DESCRIPTION
**Pull request by JackStromberg**
Add execute permission to allow script to run

### CODE REVIEW

**Comment by thomascube** [comment]
What is this change good for? There is no file named `/entrypoint.sh` and we already have `COPY --chmod=0755` for this.

**Comment by thomascube** [comment]
Again my question: Why this PR? `COPY --chmod=0755` should do the job. RUN chmod adds another layer to the image which I'd like to avoid.

**Comment by JackStromberg** [comment]
Sorry, typo.  Corrected to docker-entrypoint.sh.  Without this change, I receive the following:
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/docker-entrypoint.sh": permission denied: unknown.

Even then, I still have to run this container in privileged mode.  I don't think the COPY chmod job is working as intended.

**Comment by thomascube** [comment]
@JackStromberg You're the first to report such an issue and the docker images are built this way for a long time already. Before just changing the Dockerfile, I'd like to investigate this a bit more. Can you describe your environment where you experience the error you described above?

**Comment by JackStromberg** [comment]
I've tried two difference machines with greatly different versions of Docker client.  Both are running on Debain Buster (v10) on arm architecture.  Same error on both machines; the proposed fix eliminated the error in both versions.

Machine 1:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:20 2022
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Machine 2:
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 18:06:12 2019
 OS/Arch:           linux/arm
 Experimental:      false

**Comment by thomascube** [comment]
Maybe ARM makes the difference. We currently don't provide multi-arch builds. Do you build the images yourself?
The `--chmod` option for `COPY` commands is a feature from Docker Buildkit and thus needs to be enabled with `DOCKER_BUILDKIT=1 docker build ...`.

**Pull request closed without merging**
