### PR TITLE
Add templates

### LINKED ISSUE #5: Use a Dockerfile.template to generate both php variant
There isn't many differences between the apache and fpm version, and the entrypoint is identical.

Using a Dockerfile.template with an `update.sh` script to generate / update the variants would make maintenance much easier.

For reference:
- https://github.com/nextcloud/docker/blob/master/update.sh
- https://github.com/nextcloud/docker/blob/master/Dockerfile-debian.template

### PR DESCRIPTION
**Pull request by J0WI**
This does close #5 for real.

### CODE REVIEW

**Comment by madmath03** [comment]
Hi @thomascube ,

I let you review this since you said you needed this to work on Mac.

**Comment by J0WI** [comment]
Requirements are described in https://github.com/roundcube/roundcubemail-docker/pull/20#issuecomment-442113654

**Comment by J0WI** [comment]
@thomascube I just rebased this again, would be great to get this finally done :smiley:

**Comment by thomascube** [comment]
Templates have been implemented. Let's look at the `generate-stackbrew-library.sh` topic in a separate PR.

**Pull request closed without merging**
