### PR TITLE
Add docker-compose

### LINKED ISSUE #51: Improve CI with docker-compose
It would actually be nice to improve Travis CI with docker-compose tests.

This would:
* improve the documentation of the container by providing sample docker-compose configuration
* help maintainers to check that the container runs (and not just compiles) on PR

### PR DESCRIPTION
**Pull request by madmath03**
:construction_worker: Add docker-compose & close #51

### CODE REVIEW

**Comment by thomascube** [comment]
Nice! I'd like to see an example of a mailserver component being part of the sample docker-compose files. For example [tvial/docker-mailserver](https://hub.docker.com/r/tvial/docker-mailserver).

**Comment by madmath03** [comment]
I've been using `tvial/docker-mailserver` before so "_just_" adding it to the docker-compose would be easy, but what would be the objective of doing that ?
Is it only for documentation purposes or do you have something else in mind ?
Setting up RC to use the mail server and execute some operations (like login and or sending mail) would certainly be nice but quite harder to implement.

**Comment by thomascube** [comment]
Yes, it's more for a documentation purpose. Could also be added as commented block or just in a README. Just for the sake of having all components together.

**Comment by madmath03** [comment]
Works for me.
I will add it as a commented section of the docker-compose since it would be counterproductive to have the CI fail due to the mail server.

Should be able to add it by the end of this week.

**Comment by madmath03** [comment]
@thomascube Just added the sample mailserver config (commented) to the docker-compose.
Let me know if that works for you.

**Pull request merged**
