### PR TITLE
Add GnuPG dependence

### PR DESCRIPTION
**Pull request by J0WI**
GnuPG has been removed from newer base images.

### CODE REVIEW

**Comment by thomascube** [comment]
Fixed by commit a194c2cfad2f

**Comment by J0WI** [comment]
@thomascube you should remove `fetchDeps` afterwards

**Comment by thomascube** [comment]
@J0WI As you can see in the commit message, gnupg is left deliberately in order to enable server-side encryption using the Enignma plugin. That however still needs testing but the goal is to make this work. I'm working on it...

**Comment by J0WI** [comment]
@thomascube I would add it before the PHP dependencies then to speed up builds.

**Pull request closed without merging**
