### PR TITLE
Tweaking config and doc about secured auth

### PR DESCRIPTION
**Pull request by LupusMichaelis**

### CODE REVIEW

**Comment by thomascube** [comment]
Please understand that we deliberately limited the selection of env variables and we don't want to map each possible config option via env. For specific configurations (like `smtp_auth_type`) we suggest to use custom config files as described in the readme.

We like the TLS hint you suggested, though.

**Comment by LupusMichaelis** [comment]
OK, do I need to amend the PR?

**Comment by thomascube** [comment]
> OK, do I need to amend the PR?

Not necessarily. We'll just pick up that change in the next release. I'll keep the PR open just as a reminder for it.

**Comment by thomascube** [comment]
README.md was updated accordingly

**Pull request closed without merging**
