### PR TITLE
Add rsync

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by thomascube** [comment]
Does this PR mean the Docker images didn't work until now?

**Comment by J0WI** [comment]
The image works, but I feel a bit uncomfortable with the  update process.
We could replace https://github.com/roundcube/roundcubemail-docker/blob/d9e6fadaab91fc43cffbf2a79b8c97bee1614c63/fpm-alpine/docker-entrypoint.sh#L13
with `installto.sh` in future. This would also update the source in the docker volume if you pull a newer version of the container.

**Comment by robin-thoni** [comment]
> The image works, but I feel a bit uncomfortable with the update process.

Why using a volume at first place?

This "install" at runtime is really weird to me. Can you explain the goal of this design? I'd rather let the user choose what they want to export.

**Comment by J0WI** [comment]
> This "install" at runtime is really weird to me. Can you explain the goal of this design?

This is useful if you use the FPM variant which needs to share the files with a webserver.

**Comment by thomascube** [comment]
Fixed in commit 58f49d1.

**Pull request closed without merging**
