### PR TITLE
Add Alpine Linux variant

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by thomascube** [comment]
Before adding more variants, we should consider issue #5

**Comment by J0WI** [comment]
The Alpine image would need a separate template, because it's not that similar to the Debian variants.

**Comment by madmath03** [comment]
Indeed, you need a separate template for alpine.

Other projets usually setup a debian template and an alpine template. The entrypoint usually is the same though.

**Comment by J0WI** [comment]
@thomascube this does now also fix #5 (`update.sh`). Debian builds are currently broken (#16).

**Comment by J0WI** [comment]
See #20

**Pull request closed without merging**
